Filter retrieved results
rathrio/lists pull request #19
Opened 2017-02-27 16:06 UTC by simplay

WIP

2017-02-27 21:17 UTC, simplay commented
@rathrio: this PR is ready for a review. 👍

2017-02-27 22:02 UTC, rathrio requested changes
This is really cool. Thank you!

2017-02-27 22:02 UTC, rathrio commented on app/scrapers/fuzzy_substring_match_filter.rb
> +  # @param s [String] word to split
s -> word?

2017-02-27 22:02 UTC, rathrio commented on app/scrapers/fuzzy_substring_match_filter.rb
> +# by our scappers and is used within the ScraperResultsController class.
scappers -> scrapers

2017-02-27 22:02 UTC, rathrio commented on test/scrapers/fuzzy_substring_match_filter_test.rb
> +    gt = [
I'm having trouble figuring out what `gt` stands for 😅 ...Can you write it out?

2017-02-27 22:02 UTC, rathrio commented on test/scrapers/fuzzy_substring_match_filter_test.rb
> +end
Really comprehensive tests! 👍 👍

2017-02-27 22:02 UTC, rathrio commented on app/scrapers/fuzzy_substring_match_filter.rb
> +class FuzzySubstringMatchFilter
As discussed, move to `app/filters`.

2017-02-27 23:20 UTC, simplay commented
PR is ready to go.

2017-02-28 06:11 UTC, rathrio approved these changes

2017-02-28 06:12 UTC, rathrio commented
👍

2017-02-28 06:12 UTC, merged